---
title: "Figure S3"
date: "`r Sys.Date()`"
output: 
    rmarkdown::html_vignette:
        fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Figure S3}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  message = FALSE,
  warning = FALSE,
  cache = TRUE
)
```

```{r include=FALSE}
# switch to the project-specific library if you have one (e.g. in the companion
# docker container)
library(switchr)
if (file.exists(file.path(switchrBaseDir(), "supt4h1"))) {
  switchrNoUnload(TRUE)
  switchTo("supt4h1")
}
```

```{r include=FALSE}
library(SUPT4H1)
library(dplyr)
library(ggplot2)
theme_set(theme_linedraw(base_size = 14))
```

## Figure S3B: RNAse treatment

```{r fig.width=5, fig.height=3.5, fig.show='hold', fig.cap="Figure S3B: Flow cytometry assay performance with / without RNAse", cache=FALSE}
dat <- load_flow_data("RNAse") %>%
  dplyr::mutate(condition = dplyr::recode(condition, "RNAse" = "+ RNAse",
                                          "no_RNAse" = "- RNAse"))
plot_flow_density(dat, red = "+ RNAse", grey = "- RNAse") +
  scale_x_continuous(trans = scales::log10_trans(),
                     breaks = c(1e3, 2e3, 4e3, 8e3, 1.6e4, 3.2e4)) +
  coord_cartesian(xlim = c(1e3, 0.5e5))
```
